/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntityModelStrategy } from './entityModelStrategy';

export type _CollectionModelEntityModelStrategyEmbedded = {
  strategies?: EntityModelStrategy[];
};
