/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradeResponse } from './tradeResponse';

export type _CollectionModelTradeEmbedded = {
  trades?: TradeResponse[];
};
