/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelTradeEmbedded } from './_collectionModelTradeEmbedded';
import type { Links } from './links';

export interface CollectionModelTrade {
  _embedded?: _CollectionModelTradeEmbedded;
  _links?: Links;
}
