/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';
import type { Binary } from './binary';

export interface EntityModelTradeScreenshot {
  _links?: Links;
  image?: Binary;
  tradeId?: string;
}
