/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';

export interface EntityModelStrategy {
  _links?: Links;
  accountId: string;
  description?: string;
  name: string;
  notes?: string;
  steps?: string[];
  tags?: string[];
}
