/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type EntityModelTradeDirection =
  (typeof EntityModelTradeDirection)[keyof typeof EntityModelTradeDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityModelTradeDirection = {
  LONG: 'LONG',
  SHORT: 'SHORT',
} as const;
