/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Link {
  deprecation?: string;
  href?: string;
  hreflang?: string;
  name?: string;
  profile?: string;
  templated?: boolean;
  title?: string;
  type?: string;
}
