/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Strategy {
  accountId: string;
  description?: string;
  id?: string;
  name: string;
  notes?: string;
  steps?: string[];
  tags?: string[];
}
